### ISSUE TITLE
About thumbnail display of folders

### ISSUE THREAD

**Issue by taka0913** [hjyssg/ShiguReader#100]
Long time no see!
I will write about the points that I found inconvenient after using shigureader for a while.

When I search for a cartoon folder from "home" in the current shigureader, the folders are listed as strings.
But in many cases, it's more convenient to see folders as thumbnails rather than strings.
My suggestion is to display thumbnails instead of strings if there are files such as .zip under the folder.

**Comment by hjyssg** [comment]
I considered this feature before.
There is no technical difficulty doing this, but rather a UI design problem.

![image](https://user-images.githubusercontent.com/3008723/99971902-cc609680-2dd8-11eb-8e59-b6cebebbbb7c.png)

Currently, zips file and image folders display thumbnail as above show.
If folders that have zip also display thumbnail, where should I the new thumbnail put on webpage?

I need a UI design.  The UI of folder page is already quite messy. 
If you can provide a design draft, I can think about implementing it.

Actually, I hope some UI designer can join project. I am not very satisfied with the current UI.

**Comment by taka0913** [comment]
Certainly there is such a problem.
I'm not good at UI design, but I thought about it. 
How about a design like this?
<img width="610" alt="99971902-cc609680-2dd8-11eb-8e59-b6cebebbbb7c-copy" src="https://user-images.githubusercontent.com/30193809/100072254-58c59480-2e7f-11eb-9ba8-2269aebb3ccd.png">

Please let me know if there are any improvements to this design.

**Comment by hjyssg** [comment]
Your suggestion is good.  I like it.
But the another problem is that, how to sort them?
Currently, we use the sort bar to sort comic books accodring to their time/file size/etc. 

If we put them togther in one grid , how do we decide the order?

**Comment by hjyssg** [comment]
If we have two thumbnail grid, one for fodler, another for comic books. 

The UI will be too complicate. Since we shows may too many thumbnails.

**Comment by hjyssg** [comment]
![image](https://user-images.githubusercontent.com/3008723/100097799-05ac0b80-2e98-11eb-86df-0a7490e4a230.png)

I implemented the folder-shape UI https://github.com/hjyssg/ShiguReader/pull/101
Such that users can tell which one is zip, which one is folder much more easily.

**Comment by taka0913** [comment]
Hmm ... I see why you can't do that.
The sorting problem is difficult, as you say.
I find it difficult to display folders and files in the same place.
Therefore, the existing display part displays only the file as a thumbnail.
Then, add a new column to display the folder like an image.

<img width="769" alt="99971902-cc609680-2dd8-11eb-8e59-b6cebebbbb7c-copy2" src="https://user-images.githubusercontent.com/30193809/100098374-4e1bf700-2ea1-11eb-9e5a-d288e1a51b0c.png">

It could be a pretty big change.
How about that?

**Comment by hjyssg** [comment]
Folders that has image and zip files are both classified as "comic book" in the code.Puting them into two grid will be a huge workload.
Also two-grid design does not look good on mobile or small screen.
So I think I will continue putting them in one grid.

**Comment by taka0913** [comment]
Certainly there is a problem.
I didn't consider using it on my iPad or iPhone.
However, mixing folders and files in one grid causes sorting problems.

![100097799-05ac0b80-2e98-11eb-86df-0a7490e4a230-1](https://user-images.githubusercontent.com/30193809/100216479-ae6c7080-2f55-11eb-851e-c3896b0240f6.jpg)

So my suggestion is to make the files appear to be in a virtual folder called "Others" in the case of a mix of folders and files.

![100097799-05ac0b80-2e98-11eb-86df-0a7490e4a230-2](https://user-images.githubusercontent.com/30193809/100216515-b75d4200-2f55-11eb-96ee-bba7ad89ec59.jpg)

This will solve the sorting problem.
Since the "Others" folder does not actually exist, I think you should fix it at the beginning or end so that it will not be affected by sorting.
You may want to change the folder color to something else, such as blue, instead of orange for clarity.

**Comment by taka0913** [comment]
By the way, "Majo no tabi" is interesting!
In Japan, it's just broadcast on TV so I watch it every week.
Mr. hjyssg seems to have something that has not been translated.
Can you read Japanese?

**Comment by hjyssg** [comment]
はい、そうです。日本語は読めますよ。日本語で書き込んでもぜんぜん大丈夫です。

----
魔女の旅について
3話以外全部高評価。
イレイナちゃん可愛かったです。銀髪はすごくいい。

**Comment by taka0913** [comment]
あ、やっぱり日本語読めるんですね！英語は苦手なので、日本語が通じると助かります。

確かに3話は後味が悪かったです、、、
hjyssgさんは中国の方ですか？

**Comment by hjyssg** [comment]
はい、中国人です。

**Comment by taka0913** [comment]
githubのissueではなく、もしよければshigureaderの改善や、気軽にアニメ・マンガのお話などを別のツールでやり取りしませんか？
中国のコミュニケーションツールはwechatしか使っていませんが、wechatはどうでしょう？

**Comment by hjyssg** [comment]
いいですよ、私のwechat IDは「hjyssg1992」です。

日本人はtwitterとlineをよく使うみたい。
私twitterもよく使っています。ツイター idは「hjyssg」。
（この垢はアニメ画像集め用なので、ちょっと見苦しいかもしれません）
