### ISSUE TITLE
请问这个repo是什么license

### ISSUE THREAD

**Issue by totorowechat** [hjyssg/ShiguReader#122]

**Comment by hjyssg** [comment]
我不懂什么license。
随便拿去改，但绝对不许把我的信息全部删了。当作自己的去发布。
pull request的code review比较严格，希望按照原来写法修改

**Comment by totorowechat** [comment]
那建议使用MIT协议。保留署名的同时，代码造成的问题不负任何责任。

[这是github如何添加协议的官方doc](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository)
