### ISSUE TITLE
cannot create output folder

### ISSUE THREAD

**Issue by lszshww** [hjyssg/ShiguReader#127]
[imageMagickHelp]] D:\Downloads\本\NON-H\atelier Tiv artworks (Tiv)\(C90) [atelier Tiv artworks (Tiv)] Lily triangle closet (よろず).zip cannot create output folder

**Comment by hjyssg** [comment]
Please try running the cmd as administrator.
This happens because your computer does not allow Shigureader to create the output.

**Comment by lszshww** [comment]
npm WARN ShiguReader@1.5 No repository field.
npm WARN ShiguReader@1.5 No license field.

**Comment by hjyssg** [comment]
> npm WARN ShiguReader@1.5 No repository field.
> npm WARN ShiguReader@1.5 No license field.

fixed
