### ISSUE TITLE
Disable access to other paths

### ISSUE THREAD

**Issue by krispykiq** [hjyssg/ShiguReader#187]
When the path is 'C:\Users\User\Desktop\Test' the previous folders are also accessible. Which means other people can see files you might not want them to see. Also is there a way to disable the downloads folder? I didn't add that path but its there.

**Comment by hjyssg** [comment]
You can modify ShiguReader\src\server\routes\homePagePath.js file to decide which path you want to user to see.

If you want to more advanced file access controlling features. For example, user A can view file a, but user B cannot.  You can implement yourself, or pay me to do.
