### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hjyssg** [hjyssg/ShiguReader#2]
1. video player
2. ehentai script

**Comment by simon300000** [comment]
electron？
executable? (https://github.com/zeit/pkg)

**Comment by hjyssg** [comment]
@simon300000 

pkg is not very unstable. 
https://github.com/hjyssg/ShiguReader/issues/12

I spent almost two days on it. It didn't work out. 
I can compile everything into exe. But its snapshot file system makes every path in my code broken.

**Comment by hjyssg** [comment]
todo都实现了 close这个issue
