### ISSUE TITLE
能否release新的EXE版本？

### ISSUE THREAD

**Issue by Asterecho** [hjyssg/ShiguReader#208]
大大能否release新的EXE版本？

**Comment by hjyssg** [comment]
现在代码依赖sqlite。
sqlite依赖打包成exe，各种bug。暂时放弃

**Comment by hjyssg** [comment]
@Asterecho 能打包成exe了，能帮忙测试吗

**Comment by Asterecho** [comment]
可以帮忙测试，感谢大大!

**Comment by hjyssg** [comment]
https://github.com/hjyssg/ShiguReader/releases/tag/3.0.0-alpha 

@Asterecho 帮我试试
