### ISSUE TITLE
请问有更新docker版的计划吗

### ISSUE THREAD

**Issue by sonofrain** [hjyssg/ShiguReader#222]
我看dockerhub上的tag也是很久以前的了

**Comment by hjyssg** [comment]
我没用过docker，是之前另一个人写的readme。
现在不是还有可以直接执行的exe吗？

**Comment by hjyssg** [comment]
我倒是可以看看教程试试啊

**Comment by sonofrain** [comment]
期待！因为我一直挂在linux上的，docker对我来说方便一点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月25日(周四) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjyssg/ShiguReader] 请问有更新docker版的计划吗 (Issue #222)




 
我倒是可以看看教程试试啊
