### ISSUE TITLE
请求一个新版docker更新

### ISSUE THREAD

**Issue by fenfenyangyangmate** [hjyssg/ShiguReader#233]
我试着在群晖上部署最新版的shigureader，一直无法运行，只能用docker了，应该是我没找到修改漫画目录的配置导致的
这是我在本地ubuntu上测试的报错
![屏幕截图 2023-11-10 142313](https://github.com/hjyssg/ShiguReader/assets/90970696/cba4688d-5f08-4da0-8417-3fe3d2c58a5c)
![屏幕截图 2023-11-10 142433](https://github.com/hjyssg/ShiguReader/assets/90970696/2447d498-e843-421d-bc62-6105b10d5778)

**Comment by hjyssg** [comment]
我最近买了一个便宜的群晖的nas，可是完全没折腾。

**Comment by fenfenyangyangmate** [comment]
最近机器出问题送修了，也折腾不了了
