### ISSUE TITLE
Production 模式下的问题

### ISSUE THREAD

**Issue by mmqmzk** [hjyssg/ShiguReader#32]
我搭在自己的家用服务器上, 用 nginx 反代内网服务, dev 模式下, 把 `/` 转到 `localhost:3000`, 把 `/api` 转到 `localhost:4000/api` (我把 src 里面的 8080 全改成 4000 了), 可以正常工作. 但是在 Production 模式下, 貌似只有一个端口 `4000`, 把所有请求转到 `localhost:4000`, 会出现阅读页 404.
Nginx 的日志:

```
 [03/May/2020:10:00:11 +0800] "GET /onebook/2691019969 HTTP/2.0" 404 152 "https://*****:444/explorer/1381105937" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
```

访问 `localhost:4000/onebook/2691019969` 也是 404
![image](https://user-images.githubusercontent.com/2217694/80896979-ab463480-8d26-11ea-96fd-3f4d488a3415.png)

请教哪里有问题?

**Comment by hjyssg** [comment]
server/index.js
 const port = isProduction? 3000: 8080;
 const server = app.listen(port, () => {


没有很看懂你的意思。我没搞过nginx
解释一下，production只用一个3000的端口。dev模式下，express用的是8080，前端webpack用的是3000的端口。

**Comment by mmqmzk** [comment]
不好意思, 检查了一下, 好像是我把 nginx 配错了

**Comment by mmqmzk** [comment]
发现非本地访问, 没有移动和删除漫画的功能, 应该是 [这里](https://github.com/hjyssg/ShiguReader/blob/b85ca8d2ce392fa62a61cf2c7c34924e16d2ac48/src/client/subcomponent/FileChangeToolbar.js#L153) 限制了, 建议加个可信域名配置吧, 有时候需要远程管理.

**Comment by hjyssg** [comment]
你觉得该怎么加？

**Comment by hjyssg** [comment]
加域名多麻烦 还不如搞个账号密码系统

**Comment by mmqmzk** [comment]
前端的 webpack 不怎么懂, 可不可以在 user-config.js 里面 export 一个数组, 默认包含 localhost, 127.0.0.1, 用户可以自己加域名, 如果 localtion.hostname 包含任意一个可信域名就开启管理功能

**Comment by mmqmzk** [comment]
有 https 直接加个 basic auth 就行了吧, 我就是这么做的
有办法把服务映射到公网的用户应该知道怎么弄

**Comment by hjyssg** [comment]
设计是纯LAN使用
映射到公网不安全
服务器的删除api没安全性检查的
别人很容易就可以把你电脑东西删光

**Comment by hjyssg** [comment]
我加个输密码开启删除权限

**Comment by mmqmzk** [comment]
统一用 https auth 保护, 应该问题不大

**Comment by hjyssg** [comment]
后端我不熟，你改一个https auth我看一下

**Comment by mmqmzk** [comment]
![image](https://user-images.githubusercontent.com/2217694/80898474-6a561c00-8d36-11ea-8c2d-b0e7fc898fc0.png)


未认证无法访问 /api

**Comment by mmqmzk** [comment]
> 后端我不熟，你改一个 https auth 我看一下

这个是在 nginx 里面配的

```
  location / {
    auth_basic "Restricted access";
    auth_basic_user_file /etc/nginx/htpasswd.conf;
    proxy_buffering off;
    proxy_pass http://127.0.0.1:3000;
  }
```

当然要自己搞域名和证书
域名最便宜的可以用花生壳的二级域名, 十几块一个貌似可以长期使用, 正式的 (正式的就不建议花生壳了) 大概 100 多每年, 证书用 lets encrypt, 免费.

**Comment by mmqmzk** [comment]
没有 https 的话, basic auth 和账号密码都不安全, 不建议架到外网, 所以这方面就提供个指导让用户自己搞吧.

**Comment by mmqmzk** [comment]
看到更新密码认证了, 这样也可以吧, 不过得提醒用户, 没有 https 真的不能搞到外网
