### ISSUE TITLE
node src/server/index.js 可不可以跑在自定义端口呢？

### ISSUE THREAD

**Issue by liwufan** [hjyssg/ShiguReader#35]
因为我在8080端口开了nginx，端口被占用的时候会报错无法运行程序。

> [file-iterator] scan: 0
[0] events.js:292
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE: address already in use :::8080
[0]     at Server.setupListenHandle [as _listen2] (net.js:1314:16)
[0]     at listenInCluster (net.js:1362:12)
[0]     at Server.listen (net.js:1448:7)
[0]     at Function.listen (/home/liwufan/codes/ShiguReader/node_modules/express/lib/application.js:618:24)
[0]     at init (/home/liwufan/codes/ShiguReader/src/server/index.js:195:24)
[0]     at Object.<anonymous> (/home/liwufan/codes/ShiguReader/src/server/index.js:1005:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:1185:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1034:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:923:14)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (net.js:1341:8)
[0]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 8080
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by liwufan** [comment]
抱歉，才发现production模式没冲突

**Comment by hjyssg** [comment]
我会回头把port写成可以设置。

**Comment by hjyssg** [comment]
笔记

//will be used in production and dev mode
module.exports.http_port = 3000;

//will be used in dev mode
module.exports.dev_express_port = 8080;


const portConfig = require('./src/portConfig');
//webpack.config.js 

const {http_port, dev_express_port } = portConfig;

// devServer: {
//     port: http_port,
//     open: false,
//     host: '0.0.0.0',
//     disableHostCheck: true,
//     historyApiFallback: true,
//     publicPath: "/",
//     proxy: {
//       '/api': `http://localhost:${dev_express_port}`
//     }
//   }


const portConfig = require('../portConfig');
//in server/index.js


const port = isProduction? http_port: dev_express_port;
const server = app.listen(port, () => {
    console.log("----------------------------------------------------------------");
    console.log(`Listening on port ${port}`);
    console.log("init done");
    console.log("You can open ShiguReader from Browser now!");
    console.log(`http://localhost:`+http_port);
    console.log("----------------------------------------------------------------");
});



//   "dependencies": {
//     "is-linux": "^1.0.1",
//     "is-osx": "^1.0.2",
//     "is-windows": "^1.0.0",


'use strict';
var isLinux = require('is-linux'),
	isOsx = require('is-osx'),
	isWindows = require('is-windows'),
	cp = require('child_process');

 function shutdown (cb) {
    //modify https://github.com/hemanth/power-off/
	var cmd = '';

	if(isLinux() || isOsx()) {
		cmd = 'sudo shutdown -h now';
	} else if(isWindows()) {
		cmd = 'shutdown /s /p /s';
	} else {
		throw new Error('Unknown OS!');
	}

	cp.exec(cmd, function (err, stdout, stderr) {
		cb && cb(err, stdout, stderr);
	});
};


app.post('/api/shutdownServer', function (req, res) {
    shutdown();
    res.sendStatus(200);
});




onclickShutDown(){
    Swal.fire({
        title: "Remote Shutdown",
        text:  "Do you want to shut down your computer?",
        showCancelButton: true,
        confirmButtonText: 'Yes',
        cancelButtonText: 'No'
    }).then((result) => {
        if (result.value === true) {
            Sender.post('/api/shutdownServer', {}, res =>{
                //send another request  to check if shut down?
                alert("You computer is shut down");
            });
        } 
    });
}

{ !clientUtil.isLocalHost() && <button onClick={this.onclickShutDown.bind(this)}> Recomote shutdown </button> }








// explorerPage.js
// row 366

dirs = this.dirs;
videos = this.videoFiles;
files = this.getFilteredFiles();

askServer(){
    const hash = this.getHash();
    if (hash && this.loadedHash !== hash && this.failedTimes < 3) {
        if(this.getMode() === MODE_TAG){
            this.requestSearch();
        } else if(this.getMode() === MODE_AUTHOR){
            this.requestSearch();
        } else if (this.getMode() === MODE_SEARCH){
            this.requestTextSearch();
        } else {
            this.requestLsDir();
        }
    }else if(this.getMode() === MODE_HOME){
        
    }
}


requestHomePagePathes() {
    Sender.post("/api/homePagePath", { }, res => {
        this.handleRes(res);
    });
}


app.post('/api/homePagePath', function (req, res) {
    let homepathes = userConfig.path_will_scan;
    //check if pathes really exist
    res.send({
        dirs: homepathes
    })
});

**Comment by hjyssg** [comment]
现在改 port_config.js 就可以了
