### ISSUE TITLE
文件名包含某些字符的图片显示不出来

### ISSUE THREAD

**Issue by mmqmzk** [hjyssg/ShiguReader#40]
大概是大于 7MB 的, 一般的漫画没有这么大的, 但是有的扫图组会搞很大的封面

**Comment by hjyssg** [comment]
你电脑和浏览器吧不行。

![image](https://user-images.githubusercontent.com/3008723/81067505-5581b000-8f11-11ea-899a-8c6dc65d8b84.png)

哈哈哈

**Comment by mmqmzk** [comment]
仔细检查了一下, 更文件大小无关, 是文件名包含 `#`
文件名 `MJK-16-D400-#000.png`, 浏览器请求地址 `../cache/%E6%88%90%E5%B9%B4%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%20[%E3%81%BF%E3%81%A1%E3%81%8D%E3%82%93%E3%81%90]%20%E4%B8%BB%E5%BE%93%E3%81%88%E3%81%8F%E3%81%99%E3%81%9F%E3%81%97%E3%83%BC2020-05-10%20886%20/MJK-16-D400-`, 井号后面的没有了

**Comment by hjyssg** [comment]
url encoding的事情 回头慢慢修

**Comment by hjyssg** [comment]
encodeURIComponent

**Comment by hjyssg** [comment]
module.exports.getUrl = function (fn){
    return "../" + encodeURIComponent(fn);
}

**Comment by hjyssg** [comment]
const generateContentUrl = function (pathes, outputPath) {
    const files = [];
    const dirs = [];
    const musicFiles = [];
    
   if(!pathes){

   }
}

**Comment by hjyssg** [comment]
修了

**Comment by mmqmzk** [comment]
谢谢大大😁
