### ISSUE TITLE
更新以后 production 模式访问 /onebook/xxxx 报 404

### ISSUE THREAD

**Issue by mmqmzk** [hjyssg/ShiguReader#50]
用 `npm run dev` 启动, 可正常使用
用 `npm start` 启动, 访问 `/onebook/xxxx` 报 404, `Can't get /onebook/xxxx`, 第一次点进 `/explorer/xxxx` 正常, 刷新也是报 404.

**Comment by hjyssg** [comment]
昨天重构后端，不小心删了一段。你拉一下最新。

**Comment by mmqmzk** [comment]
辛苦了
