### ISSUE TITLE
Succeeded in running on synology NAS

### ISSUE THREAD

**Issue by taka0913** [hjyssg/ShiguReader#90]
Below are the steps I took.

Nodejs is installed on the synology NAS.

Install Java on your NAS.
However, my NAS did not need to be installed because the CPU is arm v7.

If you don’t already have a ‘shared folder’ for your Comics, create one.

Enter administrator mode with "sudo -i".
>sudo -i

Install entware-ng. It's a package manager and you can easily install imagemagick.
https://github.com/Entware/Entware-ng

Install imagemagick with entware-ng.
>opkg install imagemagick

Install git.
>opkg install git
>opkg install git-http

>git clone https://github.com/hjyssg/ShiguReader

modify src/path-config.
replace "D:" to "/volume1" 
for example "/volume1/Comic" if shared folder is "Comic".

modify src/config/user-config.js.
replace "D:" to "/volume1" 
replace "\\" to "/"
for example "/volume1/Comic/_Happy_Lesson/_Going_to_sort/_good/"

7z is included in Synology NAS as standard, but there was a problem, so install it separately.
>opkg install p7zip

>cd ShiguReader

>npm install
If some packages fail to install with a warning, force them to install with the "--force" command.

run.
>npm run dev

It's works.

**Comment by hjyssg** [comment]
Awesome! Thank you very much!

**Comment by taka0913** [comment]
I like this tool very much, but it is not accessible from the outside. 
That's because anyone can see the page if they know the URL.
So I hope this tool implements user login functionality.

**Comment by hjyssg** [comment]
ShiguReader is not safe when it can be accessed from public IP. The server code is not prepared for any cyber attack.

Let me guess your use case.
If you just want to watch comic or anime when you are not at home, you can just download files into you tablet.
For example, my ipad has VLC for video and ComicGlass for comic. I download file in my chrome and save them to my app. So I can read comic outside.

**Comment by hjyssg** [comment]
Or you dont want your family members see your personal comic collection even they know the URL.

Which one is your use case?

**Comment by taka0913** [comment]
I understand that it is dangerous from a security point of view. 
So I give up accessing from outside the house.
But it's also true that, as you say, I don't want my family to see the site.
Could you please add a simple password page?

**Comment by hjyssg** [comment]
Hahah, sure, I will add a simple password page.

**Comment by taka0913** [comment]
Thank you very much.
By the way, I want to remove the download button, where should I comment it out?

**Comment by hjyssg** [comment]
It is at FileChangeToolbar.js renderDownloadLink()

**Comment by taka0913** [comment]
I got these errors when I commented out.

[HPM] Error occurred while trying to proxy request /api/lsDir from 192.168.1.2:3000 to http://localhost:8080 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/getGoodAuthorNames from 192.168.1.2:3000 to http://localhost:8080 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by hjyssg** [comment]
It is totally unrelated, are you using any vpn or proxy?

**Comment by taka0913** [comment]
No. I'm not using it.

**Comment by hjyssg** [comment]
![image](https://user-images.githubusercontent.com/3008723/94274963-f6ccd980-ff78-11ea-944f-869d8fd07e9e.png)
All you need to do is as above. Not sure if you change any other code

**Comment by taka0913** [comment]
I see. I understand the cause. I commented out too much.

![image](https://user-images.githubusercontent.com/30193809/94275627-23d1ba00-ff82-11ea-8148-4d145e9cc9ec.png)

**Comment by taka0913** [comment]
It works fine. Thank you for your polite advice.

**Comment by hjyssg** [comment]
Hahah, it is my pleasure.

**Comment by hjyssg** [comment]
https://github.com/hjyssg/ShiguReader/pull/92 
I added a password page at 'password' branch.

![image](https://user-images.githubusercontent.com/3008723/94329497-17834680-ffee-11ea-90c1-4ecf1f2c9b11.png)

![image](https://user-images.githubusercontent.com/3008723/94329501-21a54500-ffee-11ea-91e8-4fb7d362db81.png)

I will merge it to dev branch later.

**Comment by taka0913** [comment]
Wow. Thank you for updating so quickly. The password page works in my environment as well.

**Comment by taka0913** [comment]
I am currently unable to generate thumbnails with an error like this.
![image](https://user-images.githubusercontent.com/30193809/94338750-a49abf80-002f-11eb-89bf-4a3532fbf889.png)

When I executed the same command with 7zip alone, I suspect that the cause of the error is the space in the file name.
![image](https://user-images.githubusercontent.com/30193809/94338777-e3307a00-002f-11eb-9cc4-13fe7474a765.png)

Also, I think it is incorrect that there is no space after the "-o" command.

**Comment by hjyssg** [comment]
Two potential reasons:

1. Your disk has no space left to save   the thumbnail
2. The title is too long. Such that the file path is too long for the OS to
save the thumbnail

**Comment by taka0913** [comment]
Thank you for your reply.
The cause was cloned to the root folder, so there wasn't enough space set.
Now I have moved the code below /volume1 so no error has occurred.
